repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.15
  hooks:
    - id: validate-pyproject
      name: Validate pyproject.toml

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: Format imports
    args: ["--profile", "black"]
    
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      name: Format code
      args: [--config, pyproject.toml]
      type: [python]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      name: Check PEP8
      args: [--config, .flake8]