repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.15
  hooks:
    - id: validate-pyproject

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: Sort imports with isort
    args: ["--profile", "black"]

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      name: Format code with black
      args: [--config, pyproject.toml]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      name: Check code style with flake8
      args: [--config, .flake8]

- repo: local
  hooks:
    - id: api-docs
      name: Generate API docs
      language: python
      entry: bash -c "sphinx-apidoc -f -o docs src && cd docs && make clean && make html"
      pass_filenames: false
      additional_dependencies:
        - sphinx
        - sphinx_rtd_theme
