repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.15
  hooks:
    - id: validate-pyproject

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    # Run the pytest
    - id: check-coverage
      name: Run Pytest and ensure
      language: system
      entry: bash -c "pdm install && pdm run test"
      language: python
      additional_dependencies:
        - pdm

- repo: local
  hooks:
    - id: api-docs
      name: Generate API docs
      language: python
      entry: bash -c "pdm install && pdm run doc"
      pass_filenames: false
      additional_dependencies:
        - pdm
