[project]
name = "unit-grader"
version = "1.0.0"
description = "Unit Conversion Grader a command-line interface (CLI) program that allows you to convert among units of measurement and grade the users response to determine the result."
authors = [
    {name = "simon ouyang", email = "simonouyang@gmail.com"},
]

[tool.black]
line-length = 79  # Set the maximum line length to 79 characters (following PEP 8).
target-version = ['py39']  # Set the target Python version(s), e.g., Python 3.9.

dependencies = [
    "altgraph==0.17.2",
    "click==8.1.7",
    "colorama==0.4.6",
    "coverage==7.3.2",
    "exceptiongroup==1.1.3",
    "future==0.18.2",
    "iniconfig==2.0.0",
    "macholib==1.15.2",
    "markdown-it-py==3.0.0",
    "mdurl==0.1.2",
    "numpy==1.26.1",
    "packaging==23.2",
    "pip==23.3.1",
    "pluggy==1.3.0",
    "Pygments==2.16.1",
    "pytest>=7.4.3",
    "pytest-mock==3.12.0",
    "rich==13.6.0",
    "setuptools==68.2.2",
    "shellingham==1.5.4",
    "six==1.15.0",
    "tomli==2.0.1",
    "typer==0.9.0",
    "typing-extensions==4.8.0",
    "wheel==0.37.0",
]
requires-python = ">=3.9,<3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

