name: Build And Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Build API Documentation
        run: pdm run doc

      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v1
        with:
          production-branch: "main"
          publish-dir: "./docs/_build/html"
          deploy-message: "Deploy from GitHub Actions"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: false
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Print Notice
        uses: actions/github-script@v6
        env:
          NETLIFY_URL: ${{ steps.netlify.outputs.deploy-url }}
        with:
          script: |
            const {NETLIFY_URL} = process.env
            core.notice(`Published to: ${NETLIFY_URL}`)