name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdm
        pdm install

    - name: Run Tests
      run: pdm run pytest --cov=src/unit_grader ./tests

    - name: Lint Code
      run: pdm run lint

    - name: Format Code
      run: pdm run format

    - name: Generate Documentation
      run: |
        cd docs
        make html

    - name: Build and Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        pdm build
        pdm run twine upload dist/*
  
    - name: Deploy Documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd docs/_build/html
        git init
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Deploy documentation"
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages