# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9"]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    permissions:
      contents: write
    steps:
      # Checkout the repository 
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up PDM with cache
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: '**/pdm.lock'
        
      # Install dependencies
      - name: Install dependencies
        run: pdm sync
    
      # Build the HTML documentation using Sphinx. 
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        # Flags used here, not in `make html`:
        #  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
        #  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
        with:
          docs-folder: 'docs/'
          pre-build-command: 'pip install sphinx sphinx-rtd-theme'
          build-command: 'sphinx-build -b html -nW ./src _build/html' 
    
      # Attach the HTML output the artifacts to the GitHub Actions job, for easier inspection.  
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html/
    
      # If the change happens on the default branch, take the contents of docs/build/html and push it to the gh-pages branch.  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
