name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/version-update
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.9"]
        os: ["ubuntu-latest"]
        # os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
        cache-dependency-path: '**/pdm.lock'
  
    - name: Install dependencies
      run: pdm sync

    - name: Run Tests
      run: pdm run test

    - name: Lint Code
      run: pdm run lint

    - name: Format Code
      run: pdm run format

    - name: Spell Check
      run: pdm run spell
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/feature/version-update'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Extract branch name
      #   if: github.event_name != 'pull_request'
      #   shell: bash
      #   run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch

      # # extract branch name on pull request
      # - name: Print branch name
      #   if: github.event_name == 'pull_request'
      #   run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.9"
          cache: true
          cache-dependency-path: '**/pdm.lock'

      - name: Install dependencies
        run: pdm sync

      - name: Bot Defaults
        uses: devlooped/actions-bot@v1.0.1
        with:
          github-token: ${{ secrets.SOUYANG_GITHUB_TOKEN }}
    
      - name: Bump Patch Version
        run: |
          set -e
          git pull --no-edit origin feature/version-update
          CURRENT_VERSION=$(awk -F '"' '/^version/{print $2}' "pyproject.toml")
          pdm bumpversion --current-version $CURRENT_VERSION patch pyproject.toml src/unit_grader/__init__.py --verbose --no-configured-files
          NEW_VERSION=$(awk -F '"' '/^version/{print $2}' "pyproject.toml")
          
          # Check if there are changes before committing
          if git diff --exit-code; then
            echo "Version is not updated in pyproject.toml."
          else
            git remote set-url origin https://x-access-token:${{ secrets.SOUYANG_GITHUB_TOKEN }}@github.com/souyang/unit-grader
            git add pyproject.toml
            git commit -m "[Bot] Updating version from ${CURRENT_VERSION} to ${NEW_VERSION}"
            git push
          fi
          set +e            
    
      # - name: Create Release
      #   run: |
      #     pdm publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} 


