name: Release Pipeline

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.9"]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
        cache-dependency-path: '**/pdm.lock'

    - name: Build and Publish
      run: |
        pdm build
        pdm publish --dry-run  # Test the publication process without actually publishing
        pdm publish --repository pypi

